---
- name: include multisite checks
  include: checks.yml

# Include the tasks depending on the zone type
- name: include master multisite tasks
  include: master.yml
  when:
    - rgw_zonemaster
    - not rgw_zonesecondary
  static: False

- name: include secondary multisite tasks
  include: secondary.yml
  when:
    - not rgw_zonemaster
    - rgw_zonesecondary
  static: False

# Continue with common tasks
- name: add zone to rgw stanza in ceph.conf
  ini_file:
    dest: "/etc/ceph/{{ cluster }}.conf"
    section: "client.rgw.{{ ansible_hostname }}"
    option: "rgw_zone"
    value: "{{ rgw_zone }}"
  notify:
    - restart rgw
